# Add completions
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostfile\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$nodejs\
$golang\
$python\
$cmd_duration\
$line_break\
$character
"""

add_newline = false

[fill]
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([$ahead_behind]($style))'
ahead = "[⇡${count}](green)"
diverged = "[⇡${ahead_count}(green)][⇣${behind_count}(red)]"
behind = "[⇣${count}(red)]"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = true

[nodejs]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
